enum abstract MapPosition(Int) from Int to Int
{
	var SOUTH_ENTRANCE = 1;

	var WEST_BOTTOM_CORNER = 2;
	var WEST_TOP_CORNER = 3;
	var WEST_TOP_CORNER_CLASSROOM = 4;

	var SOUTH_TOP_HALL_BOTTOMWEST = 5;
	var SOUTH_TOP_HALL_TOPWEST = 6;

	var SOUTH_TOP_HALL_CENTER = 7;

	var SOUTH_TOP_HALL_TOPEAST = 8;
	var SOUTH_TOP_HALL_BOTTOMEAST = 9;

	var SOUTH_HALL = 10;
	var SOUTH_HALL_WEST_CLASSROOM = 11;
	var SOUTH_HALL_EAST_CLASSROOM = 12;

	var WEST_CAFE = 13;
	var CENTER_CAFE = 14;
	var CENTER_CAFE_CLASSROOM = 15;
	var EAST_CAFE = 16;

	var EAST_BOTTOM_CORNER = 17;
	var EAST_BOTTOM_CORNER_CLASSROOM = 18;

	var EAST_TOP_CORNER = 19;
	var EAST_TOP_CORNER_CLASSROOM = 20;

	public function int():Int
		return this;
}
